const countryCodes = [
  { code: '+1', country: 'US/Canada', length: 10 },
  { code: '+44', country: 'United Kingdom', length: 10 },
  { code: '+380', country: 'Ukraine', length: 9 },
  { code: '+43', country: 'Austria', length: 10 },
  { code: '+32', country: 'Belgium', length: 9 },
  { code: '+359', country: 'Bulgaria', length: 9 },
  { code: '+385', country: 'Croatia', length: 9 },
  { code: '+357', country: 'Cyprus', length: 8 },
  { code: '+420', country: 'Czech Republic', length: 9 },
  { code: '+45', country: 'Denmark', length: 8 },
  { code: '+372', country: 'Estonia', length: 7 },
  { code: '+358', country: 'Finland / Åland Islands', length: 9 },
  { code: '+33', country: 'France', length: 9 },
  { code: '+49', country: 'Germany', length: 10 },
  { code: '+30', country: 'Greece', length: 10 },
  { code: '+36', country: 'Hungary', length: 9 },
  { code: '+354', country: 'Iceland', length: 7 },
  { code: '+353', country: 'Ireland', length: 9 },
  { code: '+39', country: 'Italy', length: 10 },
  { code: '+371', country: 'Latvia', length: 8 },
  { code: '+370', country: 'Lithuania', length: 8 },
  { code: '+352', country: 'Luxembourg', length: 9 },
  { code: '+356', country: 'Malta', length: 8 },
  { code: '+373', country: 'Moldova', length: 8 },
  { code: '+377', country: 'Monaco / Vatican City', length: 8 },
  { code: '+382', country: 'Montenegro', length: 8 },
  { code: '+31', country: 'Netherlands', length: 9 },
  { code: '+47', country: 'Norway', length: 8 },
  { code: '+48', country: 'Poland', length: 9 },
  { code: '+351', country: 'Portugal', length: 9 },
  { code: '+40', country: 'Romania', length: 9 },
  { code: '+381', country: 'Serbia', length: 9 },
  { code: '+421', country: 'Slovakia', length: 9 },
  { code: '+386', country: 'Slovenia', length: 8 },
  { code: '+34', country: 'Spain', length: 9 },
  { code: '+46', country: 'Sweden', length: 9 },
  { code: '+41', country: 'Switzerland', length: 9 },
  { code: '+90', country: 'Turkey', length: 10 },
  { code: '+389', country: 'North Macedonia', length: 8 },
];

export default countryCodes;
